WITH TMP AS
(
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MF
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)

SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
FROM REST_INFO A, 
     TMP B
WHERE 1=1
    AND A.FOOD_TYPE = B.FOOD_TYPE
    AND A.FAVORITES = B.MF
ORDER BY A.FOOD_TYPE DESC