SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM
(
    SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
    FROM ANIMAL_INS
    WHERE SEX_UPON_INTAKE LIKE '%Intact%'
) I,
(
    SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
    FROM ANIMAL_OUTS
    WHERE SEX_UPON_OUTCOME LIKE '%Spayed%' OR SEX_UPON_OUTCOME LIKE '%Neutered%'
) O
WHERE 1 = 1
    AND I.ANIMAL_ID = O.ANIMAL_ID
ORDER BY I.ANIMAL_ID

