SELECT DISTINCT
       A.PRODUCT_ID,
       A.PRODUCT_NAME,
       SUM(PRICE * AMOUNT) OVER (PARTITION BY A.PRODUCT_ID) AS TOTAL_PRICE
FROM FOOD_PRODUCT A,
     FOOD_ORDER B
WHERE 1=1
      AND A.PRODUCT_ID = B.PRODUCT_ID
      AND TO_CHAR(B.PRODUCE_DATE, 'YYYYMM') = '202205'
ORDER BY TOTAL_PRICE DESC, PRODUCT_ID