SELECT C.APNT_NO,
       A.PT_NAME,	
       A.PT_NO,	
       B.MCDP_CD,	
       B.DR_NAME,	
       C.APNT_YMD
FROM PATIENT A,
     DOCTOR B,
     APPOINTMENT C
WHERE 1 = 1
     AND A.PT_NO = C.PT_NO
     AND B.DR_ID = C.MDDR_ID
     AND TO_CHAR(APNT_YMD, 'YYYYMMDD') = '20220413'
     AND C.APNT_CNCL_YN = 'N'
     AND B.MCDP_CD = 'CS'
ORDER BY
     APNT_YMD