WITH B AS(
    SELECT WRITER_ID, SUM(PRICE) AS "TOTAL_SALES"
    FROM USED_GOODS_BOARD
    WHERE 1=1
          AND STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000
) 

SELECT USER_ID, NICKNAME, TOTAL_SALES
FROM USED_GOODS_USER A,
     B
WHERE 1=1
      AND A.USER_ID = B.WRITER_ID
ORDER BY TOTAL_SALES