# SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
# FROM DEVELOPERS D
# JOIN SKILLCODES S ON D.SKILL_CODE = S.CODE
# WHERE S.NAME IN ('PYTHON', 'C#')
# ORDER BY ID


SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS D
WHERE 
SKILL_CODE & (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME = 'PYTHON'
) OR
SKILL_CODE & (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME = 'C#'
) 
ORDER BY ID

