SELECT T.YEAR, (T.MAX_SIZE - E.SIZE_OF_COLONY) AS YEAR_DEV, E.ID
FROM ECOLI_DATA E
JOIN 
    (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)) T
ON YEAR(E.DIFFERENTIATION_DATE) = T.YEAR
ORDER BY YEAR, (T.MAX_SIZE - E.SIZE_OF_COLONY) 