#전부 조인된 테이블
SELECT 
(
    SELECT SUM(SCORE)
    FROM HR_GRADE
    WHERE YEAR = '2022'
    GROUP BY EMP_NO
    ORDER BY SUM(SCORE) DESC
    LIMIT 1
) AS SCORE
, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_DEPARTMENT D # 부서 정보
JOIN HR_EMPLOYEES E # 사원 정보
ON D.DEPT_ID = E.DEPT_ID
JOIN HR_GRADE G # 사원 평가 정보
ON E.EMP_NO = G.EMP_NO
WHERE E.EMP_NO = 
( 
    SELECT EMP_NO
    FROM HR_GRADE
    WHERE YEAR = '2022'
    GROUP BY EMP_NO
    ORDER BY SUM(SCORE) DESC
    LIMIT 1
)
LIMIT 1
